FORMAT: 1A
HOST: https://cities-weather-api.onrender.com

# Weather API documentation
Weather api documentation

# Group cities

## Cities' weather [/cities/search]
Endpoint for cities' weather.

### Search [GET /cities/search]
Endpoint to searach cities' weather.

+ Attributes
    + query (string, required) - City name.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        + data (array[City]) - Cities data.

# Data Structures

# City (object)
+ code (string) - city's code.
+ name: `City name` (string, required) - City's name.
